### PR TITLE
Add support for promise

### PR DESCRIPTION
**Pull request by joesonw**
usage `yield unirest.get('https://google/com').end().exec()`

appended an `exec()` method to `Request`, thus will return a Promise object.

### CODE REVIEW

**Comment by charliemc** [comment]
Does it have promise support yet?

**Comment by yckart** [comment]
Almost a year ago... Any updates?

**Comment by jmealo** [comment]
I'd love to see this upstream.

**Comment by nijikokun** [comment]
Was going to merge this in to add promises, but it appears there is a conflict, would you like to update this pull request or want me to bake it in and close this request?

**Comment by carlskii** [comment]
Hi I'm trying to get unirest to return a promise. The above example throws an unknown method error. 

Can you provide a working example for using promises with unirest please.

**Comment by jcollum** [comment]
Sooo, ~18 months and it's not closed or merged. What's going on?

**Comment by Nephrited** [comment]
2 years on, any news? This seems fairly important.

**Comment by PymZoR** [comment]
Async/await are going to be supported soon, and still no Promise support. 👎

**Comment by born2net** [comment]
any news on getting yield to work with unirest?

**Comment by prad9** [comment]
Any update on this?

**Comment by Simobain** [comment]
Hey ! We are in 2018. 
Any news ?

**Comment by PymZoR** [comment]
Time to fork I guess

**Pull request closed without merging**
