### PR TITLE
[Euphoria] 1.0.0

### PR DESCRIPTION
**Pull request by nijikokun**
### What is changing?

Complete overhaul of the original codebase, with clean consolidated syntax and structure. Breakdown of monolithic style file into smaller chunks of code which is more maintainable. 

Unirest will not be a nested object, instead it will become an actual prototype object with extension. Parsers / Serializers are broken down into `marshallers` with two methods `marshal` and `unmarshal`. Unirest methods will be placed into their own file, allowing for better comprehension of code.

Doing the above allows for global configuration on options, meaning less code in your projects :+1:
### Todo
- [ ] Unit tests on individual files
- [x] Convert Serializer/Parsers to Data Marshallers - #43 
- [x] Global configuration
- [x] Change enum to constants - #42 
- [ ] Add Mashape header sugar method to Unirest class methods
- [ ] Add API Analytics option using Cloud Proxy

### CODE REVIEW

**Comment by Nijikokun** [comment]
Perhaps change `enum` to `constants`

**Comment by thibaultCha** [comment]
It'd be cool to have a native method to set the `X-Mashape-Key` header. Ideally, this method would be on every Unirest library but since nodejs is the most maintained one, we could start with it.

Either on individual call and as a default header for a singleton if supported by the library.

**Comment by Nijikokun** [comment]
> It'd be cool to have a native method to set the X-Mashape-Key header. Ideally, this method would be on every Unirest library but since nodejs is the most maintained one, we could start with it.
> 
> Either on individual call and as a default header for a singleton if supported by the library.

Nice idea! :+1: Yeah it can be available as a global option and as a request method!

I've added it to the todo list

**Comment by Nijikokun** [comment]
Determine whether to use `is.js` in place of our current utility which is a micro implementation, perhaps its even inspired by it since is.js is new. It's either this or using `Object.prototype.toString` to do checks.

https://github.com/arasatasaygin/is.js/issues/11

**Comment by Nijikokun** [comment]
@therebelrobot I have solidified the **core** should you still want to help out with tests

**Comment by Nijikokun** [comment]
> I'm game. Let me know what you need :) Are you familiar with Istanbul? We can add that for code coverage as well if you want.

It's already in the `Makefile`

**Comment by Nijikokun** [comment]
> I'm game. Let me know what you need :)

Currently tests for Marshallers would help out a lot

**Comment by joesonw** [comment]
Promise support?

**Comment by Nijikokun** [comment]
Yes

**Comment by nijikokun** [comment]
Since it has been a while, this needs some major review, sorry for the long update.

**Pull request closed without merging**
